import { createActions } from 'redux-actions';

export const {
  setCarouselPosts,
  setCarouselPostsError,
  setCarouselPostsSuccess,
  setFeedPosts,
  setFeedPostsError,
  setFeedPostsSuccess,
  setIsCarouselPostsLoading,
  setIsFeedPostsLoading,
  setIsPostListLoading,
  setIsTopicsLoading,
  setIsTrendingPostsLoading,
  setPostList,
  setPostListError,
  setPostListSuccess,
  setTopics,
  setTopicsError,
  setTopicsSuccess,
  setTrendingPosts,
  setTrendingPostsError,
  setTrendingPostsSuccess,
} = createActions(
  'SET_CAROUSEL_POSTS',
  'SET_CAROUSEL_POSTS_ERROR',
  'SET_CAROUSEL_POSTS_SUCCESS',
  'SET_FEED_POSTS',
  'SET_FEED_POSTS_ERROR',
  'SET_FEED_POSTS_SUCCESS',
  'SET_IS_CAROUSEL_POSTS_LOADING',
  'SET_IS_FEED_POSTS_LOADING',
  'SET_IS_POST_LIST_LOADING',
  'SET_IS_TOPICS_LOADING',
  'SET_IS_TRENDING_POSTS_LOADING',
  'SET_POST_LIST',
  'SET_POST_LIST_ERROR',
  'SET_POST_LIST_SUCCESS',
  'SET_TOPICS',
  'SET_TOPICS_ERROR',
  'SET_TOPICS_SUCCESS',
  'SET_TRENDING_POSTS',
  'SET_TRENDING_POSTS_ERROR',
  'SET_TRENDING_POSTS_SUCCESS'
);
